/**
 * Minimal sRGB ICC v2 profile, generated byte-for-byte deterministically.
 *
 * PDF/A requires an OutputIntent with an embedded ICC profile. Shipping a
 * binary .icc file would break the zero-dependency rule, so we synthesize
 * one: v2 'mntr'/'RGB '/'XYZ ' profile with the standard Bradford-adapted
 * sRGB primaries, D50 white point, and the exact sRGB transfer curve as a
 * parametric type-4 'para' element. ~700 bytes; structurally a complete,
 * standards-conformant display profile.
 */

function s15Fixed16(v: number): number {
  return Math.round(v * 65536);
}

class Bin {
  private parts: number[] = [];
  u8(v: number): this { this.parts.push(v & 0xff); return this; }
  u16(v: number): this { return this.u8(v >> 8).u8(v); }
  u32(v: number): this { return this.u8(v >> 24).u8(v >> 16).u8(v >> 8).u8(v); }
  i32(v: number): this { return this.u32(v >>> 0); }
  str(s: string): this { for (const c of s) this.u8(c.charCodeAt(0)); return this; }
  zeros(n: number): this { for (let i = 0; i < n; i++) this.parts.push(0); return this; }
  pad4(): this { while (this.parts.length % 4) this.parts.push(0); return this; }
  get length(): number { return this.parts.length; }
  bytes(): Uint8Array { return new Uint8Array(this.parts); }
}

function xyzTag(x: number, y: number, z: number): Bin {
  const b = new Bin();
  b.str('XYZ ').zeros(4);
  b.i32(s15Fixed16(x)).i32(s15Fixed16(y)).i32(s15Fixed16(z));
  return b;
}

/** sRGB transfer curve as ICC parametric curve type 4. */
function srgbTrcTag(): Bin {
  const b = new Bin();
  b.str('para').zeros(4).u16(4).u16(0);
  const g = 2.4;
  const a = 1 / 1.055;
  const c0 = 0.055 / 1.055;
  const d = 0.04045;
  const e = 1 / 12.92;
  for (const p of [g, a, c0, 0, d, e, 0]) b.i32(s15Fixed16(p));
  return b;
}

function descTag(text: string): Bin {
  const b = new Bin();
  b.str('desc').zeros(4);
  b.u32(text.length + 1).str(text).u8(0); // ASCII count + string + NUL
  b.u32(0).u32(0); // no Unicode
  b.u16(0).u8(0).zeros(67); // no ScriptCode
  return b;
}

function textTag(text: string): Bin {
  const b = new Bin();
  b.str('text').zeros(4).str(text).u8(0);
  return b;
}

// Bradford-adapted sRGB primaries (IEC 61966-2-1), D50 white point
const R_XYZ = [0.4360413, 0.2224845, 0.0139202];
const G_XYZ = [0.3851129, 0.7169058, 0.0970672];
const B_XYZ = [0.1430458, 0.0606169, 0.7139133];
const D50 = [0.9642, 1.0, 0.8249];

/** Build the profile bytes. Same call, same bytes — every time, everywhere. */
export function buildSrgbIccProfile(): Uint8Array {
  const tags: Array<[string, Bin]> = [
    ['cprt', textTag('CC0 1.0 Universal (Public Domain)')],
    ['desc', descTag('sRGB')],
    ['rTRC', srgbTrcTag()],
    ['gTRC', srgbTrcTag()],
    ['bTRC', srgbTrcTag()],
    ['rXYZ', xyzTag(...(R_XYZ as [number, number, number]))],
    ['gXYZ', xyzTag(...(G_XYZ as [number, number, number]))],
    ['bXYZ', xyzTag(...(B_XYZ as [number, number, number]))],
    ['wtpt', xyzTag(...(D50 as [number, number, number]))],
  ];

  const out = new Bin();
  // --- 128-byte header (size patched at the end) ---
  out.u32(0); // profile size placeholder
  out.str('OPDF'); // CMM: OmniPDF
  out.u32(0x02100000); // version 2.1.0
  out.str('mntr').str('RGB ').str('XYZ ');
  out.u16(2024).u16(1).u16(1).u16(0).u16(0).u16(0); // fixed creation date (determinism)
  out.str('acsp');
  out.zeros(4); // platform: none
  out.zeros(4); // flags
  out.str('OPDF'); // manufacturer
  out.zeros(4); // model
  out.zeros(8); // attributes
  out.u32(0); // rendering intent: perceptual
  for (const v of D50) out.i32(s15Fixed16(v)); // illuminant
  out.str('OPDF'); // creator
  out.zeros(44); // profile ID + reserved

  // --- tag table ---
  out.u32(tags.length);
  const tableStart = out.length;
  out.zeros(tags.length * 12); // entries patched below

  const entries: Array<{ offset: number; size: number }> = [];
  for (const [, data] of tags) {
    out.pad4();
    entries.push({ offset: out.length, size: data.length });
    for (const byte of data.bytes()) out.u8(byte);
  }

  const bytes = out.bytes();
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  view.setUint32(0, bytes.length, false); // patch profile size
  tags.forEach(([, ], i) => {
    const rec = tableStart + i * 12;
    const sig = tags[i]![0];
    for (let k = 0; k < 4; k++) bytes[rec + k] = sig.charCodeAt(k);
    view.setUint32(rec + 4, entries[i]!.offset, false);
    view.setUint32(rec + 8, entries[i]!.size, false);
  });
  return bytes;
}
